### PR TITLE
Add basic cli support

### PR DESCRIPTION
**Pull request by quangIO**
#1

### CODE REVIEW

**Comment by ducthienbui97** [comment]
I prefer using pure python.

**Comment by quangIO** [comment]
The first section of bat file is supposed to make sure python path is setup correctly (so obviously we should not write it in pure python). I can remove it, however it MIGHT cause some trouble for end users.

**Comment by ducphanduyagentp** [comment]
lol

**Comment by ducthienbui97** [comment]
@ducphanduyagentp you should contribute this repo :)

**Pull request closed without merging**
